# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]  
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: my-docker-hub-namespace/my-docker-hub-repository
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: |
              aminbh/gateway:${{ github.sha }}
              aminbh/gateway:latest
          labels: ${{ steps.meta.outputs.labels }}
  
  deploy_to_ec2:
    name: Deploy to EC2
    steps:  
      - name: Docker Pull & Run From Hub 
        uses: appleboy/ssh-action@master
        with:
          host: ec2-52-22-205-36.compute-1.amazonaws.com
          username: ghactions
          key: ${{secrets.ACTION_PRIVATE_KEY}}
          envs: GITHUB SHA
          script: |
            docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}
            docker pull ${{secrets.DOCKER_USERNAME}}/$REPO
            docker stop gateway
            docker rm gateway
            docker run -dp 1337:1337 --network TEST --name gateway gateway
